---
title: "my_final_project"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
  orientation: rows
  vertical_layout: fill
  source_code: embed
  theme: cosmo

---

```{r setup, include=FALSE}

#####Make sure you load any required packages.

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(magrittr)
library(openxlsx)
library(readxl)
library(writexl)
library(reshape2)
library(skimr)
library(janitor)
library(lubridate)
library(ggthemes)
library(plotly)
library(DT)
library(rsconnect)
library(timetk)
library(wordcloud2)


```

```{r, include=FALSE} 

readRDS("nobel.rds") -> nobel

```

# Data Table

## Column {data-width="1000"}

```{r}

DT::datatable(nobel, 
              extensions = "Buttons",
              options = list(pageLength = 100, 
                             scrollY= TRUE,
                             dom = "Blfrtip",
                             buttons = c("copy", "csv", "excel", "pdf")))


```

# Page 1

### Chart A *1. Histogram: distributions of winners by age.*



```{r data_1, echo = FALSE}
nobel %>% 
  dplyr::select(age_get_prize) -> number_1_data


####make sure you call the data so it will display in your report

number_1_data %>% 
  ggplot2::ggplot(mapping = aes(x = age_get_prize)) +
  ggplot2::geom_histogram(fill = "lightblue") +
  ggplot2::theme_minimal() +
  ggplot2::labs(title = "Histogram: distributions of winners by age",
                x = "Age get Prize",
                y = NULL) -> number_1_fig

number_1_fig

```

Page 2
======
  
### Chart B *2. Bar charts: winners by Top 10 university*


```{r data_2, echo = FALSE}
nobel %>% 
  dplyr::select(name_of_university) %>% 
  dplyr::count(name_of_university) %>% 
  dplyr::arrange(desc(n)) %>% 
  dplyr::slice_head(n = 10) -> number_2_data


####make sure you call the data so it will display in your report

number_2_data %>% 
  dplyr::slice(n = -1) %>% 
  ggplot2::ggplot(mapping = aes(y = reorder(name_of_university, n), x = n)) +
  ggplot2::geom_bar(stat = "identity",
                    mapping = aes(fill = name_of_university),
                    show.legend = FALSE) +
  ggplot2::theme_minimal() +
  ggplot2::labs(title = "Bar charts: winners by Top 10 university",
                x = "Number of Nobel Prize", 
                y = "Name of University") +
  ggplot2::geom_text(mapping = aes(label = n), hjust = "outward") -> number_2_fig


number_2_fig



```

Page 3
======

### Chart C  *3. Pie plot: average age of winners by category.*


```{r data_3, echo = FALSE}
nobel %>% 
  dplyr::select(gender, age, category) %>% 
  dplyr::group_by(category) %>% 
  dplyr::summarise(mean = mean(age)) %>% 
  dplyr::mutate(mean = round(mean, 0)) %>% 
  dplyr::arrange(desc(mean)) -> number_3_data


number_3_data %>% 
  ggplot2::ggplot(mapping = aes(x = desc(reorder(category, mean)), y = mean, fill = category)) +
  ggplot2::geom_bar(stat = "identity") +
  ggplot2::coord_polar() +
  ggplot2::geom_text(mapping = aes(label = paste0(category, " - ", mean))) +
  ggplot2::scale_y_continuous(labels = scales::number) +
  ggplot2::theme_void() +
  ggplot2::theme(legend.position = "none")+
  ggplot2::labs(title = "Average age of Winners by Category") -> number_3_fig


number_3_fig

```


Page 4
======

### Chart D  *4. Line Plot: Number of Nobel Prize received by Gende*


```{r data_4, echo = FALSE}
nobel %>% 
  dplyr::select(gender, year) %>% 
  dplyr::group_by(gender, year) %>% 
  dplyr::count() %>% 
  dplyr::ungroup()-> number_4_data
  
number_4_data %>% 
  ggplot2::ggplot(mapping = aes(x = year, y = n, group = gender)) +
  ggplot2::geom_line(mapping = aes(color = gender)) +
  ggplot2::labs(title = "Number of Nobel Prize received by Gender",
                y = "Number of Nobel Prize",
                x = "Year") +
  ggplot2::theme_classic() -> number_4_fig


number_4_fig

```


Page 5
======

### Chart E  *5. Bar Plot: Frequency by country of University*


```{r data_5, echo = FALSE}
nobel %>% 
  dplyr::group_by(country_of_university) %>% 
  dplyr::count() %>% 
  dplyr::filter(country_of_university != "") %>% 
  dplyr::arrange(desc(n))-> number_5_data


number_5_data %>% 
  ggplot2::ggplot(mapping = aes(x = n, y = reorder(country_of_university, n))) +
  ggplot2::geom_bar(stat = "identity", fill = "lightblue") +
  ggplot2::geom_text(mapping = aes(label = n), hjust = "inward", color = "tomato1") +
  ggplot2::labs(title = "Bar Plot: Frequency by country of University",
                x = NULL,
                y = NULL) +
  ggplot2::theme_minimal() -> number_5_fig

number_5_fig


```





